[package]
name = "nested-star-aggregator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nested-sta-rs = { git = "ssh://git@github.com/brave-experiments/nested-sta-rs", branch = "add-epoch-to-message" }
sta-rs = { git = "https://github.com/brave-experiments/sta-rs", branch = "public-api-changes" }
actix-web = "4"
env_logger = "0.9"
log = "0.4"
tokio = { version = "1.17", features = ["full"] }
futures = "0.3"
futures-core = "0.3"
dotenv = "0.15"
derive_more = "0.99"
hex = "0.4"
rand = "0.8"
clap = { version = "3.1", features = ["derive"] }
base64 = "0.13"
bincode = "1.3"
serde_json = "1.0"
async-trait = "0.1"
rdkafka = "0.28"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
r2d2 = "0.8"
